### ISSUE TITLE
undefined method 'k8sobject'

### ISSUE THREAD

**Issue by geofflancaster** [bgeesaman/train-kubernetes#5]
I've installed train-kubernetes but am getting an undefined method error. Any help would be appreciated.

```# inspec plugin list
┌───────────────────────────┬─────────┬──────────────┬─────────┐
│        Plugin Name        │ Version │     Via      │ ApiVer  │
├───────────────────────────┼─────────┼──────────────┼─────────┤
│ inspec-artifact           │ 4.23.11 │ core         │ 2       │
│ inspec-compliance         │ 4.23.11 │ core         │ 2       │
│ inspec-habitat            │ 4.23.11 │ core         │ 2       │
│ inspec-init               │ 4.23.11 │ core         │ 2       │
│ inspec-plugin-manager-cli │ 4.23.11 │ core         │ 2       │
│ inspec-reporter-html2     │ 4.23.11 │ core         │ 2       │
│ inspec-reporter-json-min  │ 4.23.11 │ core         │ 2       │
│ inspec-reporter-junit     │ 4.23.11 │ core         │ 2       │
│ inspec-supermarket        │ 4.23.11 │ core         │ 0       │
│ train-aws                 │ 0.1.18  │ gem (system) │ train-1 │
│ train-habitat             │ 0.2.13  │ gem (system) │ train-1 │
│ train-kubernetes          │ 0.1.5   │ gem (user)   │ train-1 │
│ train-winrm               │ 0.2.11  │ gem (system) │ train-1 │
└───────────────────────────┴─────────┴──────────────┴─────────┘
 13 plugin(s) total
```

```
# cat inspec.yml
name: initial
title: InSpec Profile
maintainer: The Authors
copyright: The Authors
copyright_email: you@example.com
license: Apache-2.0
summary: An InSpec Compliance Profile
version: 0.1.0
supports:
  platform: k8s
depends:
  - name: inspec-k8s
    #path: ../inspec-k8s  # If you fork https://github.com/bgeesaman/inspec-k8s locally, you can develop/iterate locally
    url: https://github.com/bgeesaman/inspec-k8s/archive/0.1.2.tar.gz
```

```
# inspec exec . -t k8s://

Profile: InSpec Profile (initial)
Version: 0.1.0
Target:  kubernetes://xxx.gr7.us-west-2.eks.amazonaws.com:443

  ×  Initial Deployment: Verify deployment
     ×  Control Source Code Error ./controls/initial-deployment.rb:5
     undefined method `k8sobject' for #<Inspec::Rule:0x00005629be181e40>


Profile Summary: 0 successful controls, 1 control failure, 0 controls skipped
Test Summary: 0 successful, 1 failure, 0 skipped
```
